# Generated by Django 2.2.7 on 2019-11-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191120_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='count_item_buy',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_item',
        ),
        migrations.AlterField(
            model_name='item',
            name='name_item',
            field=models.CharField(max_length=200, verbose_name='Название вещи и её стоимость'),
        ),
    ]
