# Generated by Django 2.2.7 on 2019-12-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191130_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name_item',
            field=models.TextField(max_length=200, verbose_name='Название вещи и её стоимость'),
        ),
    ]
