# Generated by Django 2.2.7 on 2019-12-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191201_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_item',
            field=models.IntegerField(default=None, verbose_name='Стоимость вещи'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_item',
            field=models.TextField(max_length=200, verbose_name='Название вещи'),
        ),
    ]
