# Generated by Django 2.2.7 on 2019-12-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20191213_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_item',
            field=models.IntegerField(default=0, verbose_name='Стоимость вещи'),
        ),
    ]
