# Generated by Django 2.2.7 on 2019-12-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20191213_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_item',
        ),
    ]
