# Generated by Django 2.2.7 on 2019-12-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_item_price_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_item',
            field=models.CharField(max_length=10, verbose_name='Стоимость вещи'),
        ),
    ]
