# Generated by Django 2.2.7 on 2019-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20191213_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_item',
            field=models.FloatField(max_length=10, verbose_name='Стоимость вещи'),
        ),
    ]
