# Generated by Django 2.2.7 on 2019-12-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20191215_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url_icon',
            field=models.TextField(default=' ', max_length=999, verbose_name='Ссылка на изображение'),
        ),
    ]
