# Generated by Django 2.2.7 on 2019-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_item_url_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name_item',
            field=models.TextField(db_index=True, max_length=200, verbose_name='Название вещи'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_icon',
            field=models.TextField(db_index=True, default=' ', max_length=999, verbose_name='Ссылка на изображение'),
        ),
    ]
