# Generated by Django 2.2.7 on 2019-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20191220_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url_icon',
            field=models.CharField(db_index=True, default=' ', max_length=999, verbose_name='Ссылка на изображение'),
        ),
    ]
