# Generated by Django 2.2.7 on 2019-12-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20191220_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name_item',
            field=models.CharField(db_index=True, max_length=400, verbose_name='Название вещи'),
        ),
    ]
