# Generated by Django 3.0.1 on 2019-12-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20191221_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name_item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price_item',
            new_name='price',
        ),
    ]
